version: 2
updates:
- package-ecosystem: nuget
  directory: "/csharp-selenium-webdriver-sample"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Selenium.WebDriver.ChromeDriver
    versions:
    - 88.0.4324.9600
    - 89.0.4389.2300
  - dependency-name: MSTest.TestAdapter
    versions:
    - 2.1.2
    - 2.2.1
  - dependency-name: MSTest.TestFramework
    versions:
    - 2.1.2
    - 2.2.1
  - dependency-name: Microsoft.NET.Test.Sdk
    versions:
    - 16.8.3
    - 16.9.1
  - dependency-name: Selenium.Axe
    versions:
    - 2.0.2
    - 2.0.3
  - dependency-name: Selenium.WebDriver.GeckoDriver
    versions:
    - 0.29.0
- package-ecosystem: npm
  directory: "/typescript-selenium-webdriver-sample"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: "@types/jest"
    versions:
    - 26.0.20
    - 26.0.21
    - 26.0.22
  - dependency-name: typescript
    versions:
    - 3.9.9
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: chromedriver
    versions:
    - 88.0.0
    - 89.0.0
  - dependency-name: axe-sarif-converter
    versions:
    - 2.6.1
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: handlebars
    versions:
    - 4.7.6
  - dependency-name: ts-jest
    versions:
    - 24.3.0
